<?php
/**
 * PromptBotBotTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BombBomb
 *
 * We make it easy to build relationships using simple videos.
 *
 * OpenAPI spec version: 2.0.22196
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PromptBotBotTest Class Doc Comment
 *
 * @category    Class */
// * @description The PromptBot\\Bot class
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PromptBotBotTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "PromptBotBot"
     */
    public function testPromptBotBot()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "userId"
     */
    public function testPropertyUserId()
    {

    }

    /**
     * Test attribute "emailId"
     */
    public function testPropertyEmailId()
    {

    }

    /**
     * Test attribute "listId"
     */
    public function testPropertyListId()
    {

    }

    /**
     * Test attribute "promptSubject"
     */
    public function testPropertyPromptSubject()
    {

    }

    /**
     * Test attribute "promptBody"
     */
    public function testPropertyPromptBody()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "startDate"
     */
    public function testPropertyStartDate()
    {

    }

    /**
     * Test attribute "endDate"
     */
    public function testPropertyEndDate()
    {

    }

    /**
     * Test attribute "botTypeId"
     */
    public function testPropertyBotTypeId()
    {

    }

    /**
     * Test attribute "templateId"
     */
    public function testPropertyTemplateId()
    {

    }

}
