<?php
/**
 * VideoEmailPromptTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BombBomb
 *
 * We make it easy to build relationships using simple videos.
 *
 * OpenAPI spec version: 2.0.20679
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * VideoEmailPromptTest Class Doc Comment
 *
 * @category    Class */
// * @description Configures a single prompt which asks a user to record a video into an outgoing email.
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VideoEmailPromptTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "VideoEmailPrompt"
     */
    public function testVideoEmailPrompt()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "userId"
     */
    public function testPropertyUserId()
    {

    }

    /**
     * Test attribute "templateId"
     */
    public function testPropertyTemplateId()
    {

    }

    /**
     * Test attribute "emailSubjectLine"
     */
    public function testPropertyEmailSubjectLine()
    {

    }

    /**
     * Test attribute "emailContent"
     */
    public function testPropertyEmailContent()
    {

    }

    /**
     * Test attribute "toEmailAddresses"
     */
    public function testPropertyToEmailAddresses()
    {

    }

    /**
     * Test attribute "toLists"
     */
    public function testPropertyToLists()
    {

    }

    /**
     * Test attribute "jerichoId"
     */
    public function testPropertyJerichoId()
    {

    }

    /**
     * Test attribute "promptSubject"
     */
    public function testPropertyPromptSubject()
    {

    }

    /**
     * Test attribute "promptHtml"
     */
    public function testPropertyPromptHtml()
    {

    }

    /**
     * Test attribute "sendWithoutVideo"
     */
    public function testPropertySendWithoutVideo()
    {

    }

    /**
     * Test attribute "videoDueDate"
     */
    public function testPropertyVideoDueDate()
    {

    }

    /**
     * Test attribute "scheduledSendDate"
     */
    public function testPropertyScheduledSendDate()
    {

    }

    /**
     * Test attribute "videoId"
     */
    public function testPropertyVideoId()
    {

    }

    /**
     * Test attribute "emailId"
     */
    public function testPropertyEmailId()
    {

    }

    /**
     * Test attribute "jobId"
     */
    public function testPropertyJobId()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "doNotApplyTemplate"
     */
    public function testPropertyDoNotApplyTemplate()
    {

    }

}
