<?php
/**
 * SocialsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BombBomb
 *
 * We make it easy to build relationships using simple videos.
 *
 * OpenAPI spec version: 2.0.24005
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * SocialsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SocialsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for getSocialArticleProperties
     *
     * Gets the social email properties.
     *
     */
    public function testGetSocialArticleProperties()
    {

    }

    /**
     * Test case for getSocialAutoShares
     *
     * Gets the auto shares from the client group assoc id.
     *
     */
    public function testGetSocialAutoShares()
    {

    }

    /**
     * Test case for getSocialPermissions
     *
     * Get permissions for social integration.
     *
     */
    public function testGetSocialPermissions()
    {

    }

    /**
     * Test case for getSocialStatus
     *
     * Gets the social state.
     *
     */
    public function testGetSocialStatus()
    {

    }

    /**
     * Test case for updateSocialAutoShares
     *
     * Gets the auto shares from the client group assoc id.
     *
     */
    public function testUpdateSocialAutoShares()
    {

    }

    /**
     * Test case for updateSocialMessage
     *
     * Sets the users social message to what they typed in.
     *
     */
    public function testUpdateSocialMessage()
    {

    }

    /**
     * Test case for updateSocialStatus
     *
     * Updates the social state for the object.
     *
     */
    public function testUpdateSocialStatus()
    {

    }

}
